FROM ubuntu:16.04

RUN apt update && apt dist-upgrade -y && apt install -y postgresql-9.5 postgresql-contrib-9.5

USER postgres

RUN /etc/init.d/postgresql start;\
 psql --command "CREATE USER conquest WITH PASSWORD 'conquestpass'";\
 createdb -O conquest conquestdb

USER root

RUN echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/9.5/main/pg_hba.conf \
 && echo "listen_addresses='*'" >> /etc/postgresql/9.5/main/postgresql.conf

EXPOSE 5432

USER postgres

CMD ["/usr/lib/postgresql/9.5/bin/postgres", "-D", "/var/lib/postgresql/9.5/main", "-c", "config_file=/etc/postgresql/9.5/main/postgresql.conf"]


