FROM tomcat:8.5

RUN apt update && apt install wget\
 p7zip-full 

COPY ./config/tomcat-users.xml /tmp

RUN cd /tmp; wget https://sourceforge.net/projects/dcm4che/files/Oviyam/2.6/Oviyam-2.6-bin.zip/download;\
 7z x download;\
 cd Oviyam-2.6-bin;\
 mv ./tomcat/* /usr/local/tomcat/lib/;\
 mv ./Oviyam-2.6-bin/*.war /usr/local/tomcat/webapps/;\
 cp /tmp/tomcat-users.xml /usr/local/tomcat/conf/
 
EXPOSE 8080
CMD ["catalina.sh", "run"]
