FROM ubuntu:16.04

RUN apt-get update &&\
 apt-get install -y g++\
 lua5.1\
 make\
 libpq-dev\
 apache2\
 wget\
 sudo

RUN mkdir /opt/conquest; mkdir /usr/local/man/man1; mkdir /var/www; mkdir /usr/bin/cgi-bin/

WORKDIR /opt/conquest

RUN wget https://ingenium.home.xs4all.nl/dicomserver/conquestlinux1417e2.tar.gz; tar -xvf *tar.gz

COPY ./config/ /tmp

RUN cp /tmp/* ./

RUN cd ./jpeg-6c; ./configure; make; make install

RUN cd ./jasper-1.900.1-6ct; ./configure; make; make install

RUN ./maklinux_postgres


EXPOSE 80

RUN a2enmod cgi

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
