# Pull OS image

FROM ubuntu:16.04

# Устанавливаем зависимости
RUN apt -y update && apt -y install wget \
 g++\
 make\
 lua5.1\
 sudo\
 apache2\
 libpq-dev



# Скачивваем и распаковываем conquest
RUN mkdir /opt/conquest; mkdir /usr/local/man/man1

WORKDIR /opt/conquest

RUN wget https://ingenium.home.xs4all.nl/dicomserver/conquestlinux1417e2.tar.gz; tar -xvf *gz

COPY ./config ./config

RUN cp ./config/* ./

RUN cd ./jpeg-6c; ./configure; make; make install

RUN cd ./jasper-1.900.1-6ct; ./configure; make; make install

RUN ./maklinux_postgres

RUN a2enmod cgi

EXPOSE 80 5678

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]



