# Pull OS image

FROM ubuntu:18.04

# Устанавливаем зависимости
RUN apt -y update && apt -y install wget \
 build-essential\
 g++\
 lua5.1\
 p7zip-full\
 sudo\
 libpq-dev



# Скачивваем и распаковываем conquest
RUN mkdir -p /opt/conquest/config; mkdir /usr/local/man/man1

WORKDIR /opt/conquest

RUN wget https://ingenium.home.xs4all.nl/dicomserver/dicomserver1419c1.zip; 7z x *.zip

COPY ./maklinux ./

RUN chmod +x ./maklinux; ./maklinux

COPY ./docker-entrypoint.sh ./docker-entrypoint.sh

RUN chmod +x ./docker-entrypoint.sh

EXPOSE 5678

ENTRYPOINT ["/opt/conquest/docker-entrypoint.sh"]
